### PR TITLE
feat: capacitor 5 support

### PR DESCRIPTION
**Pull request by AE1NS**
Closes https://github.com/aparajita/capacitor-biometric-auth/issues/6

### CODE REVIEW

**Comment by aparajita** [comment]
Did you just run the upgrade tool?

**Comment by AE1NS** [comment]
No, I didnt get the update tool work, maybe because Im using pnpm, I dont know. This PR changes are made manually. Are there issues?

**Comment by aparajita** [comment]
There's more to the upgrade than just those changes, but it's a start.

**Comment by AE1NS** [comment]
For android this should be fine. You are talking about ios right? Maybe you need to extend it, sorry. Im unfortunately no iOS professional and trusted to the migration guide iOS sentence `The vast majority of users should not experience any issues...` and hoped this plugin is not affected :)

**Comment by aparajita** [comment]
I merged your changes, thanks.

**Comment by aparajita** [comment]
Just released Capacitor 5 version.

**Pull request closed without merging**
